### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gdegani** [ForkbombEu/DIDimo#2]
GitHub doesn't recognise the licence included in the readme and categorize the project as 'licence: none'. 
It would be nice to define the license in a way that is recognised.

BTW, very interesting project.

**Comment by puria** [comment]
Ciao Giancarlo,

thanks for the interest, and let us noticing the issue!
You can track the licensing work on #3 I'll take care of that and will going to use the https://git.fsfe.org/reuse/tool so it will be easy also to have a generate a SBOM (Software Bill of Materials) in case didimo tool is used in other projects!
